# Generated by Django 4.1.7 on 2023-03-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(max_length=6),
        ),
    ]
