# Generated by Django 4.1.7 on 2023-04-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0002_alter_machine_nom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("prenom", models.CharField(max_length=6)),
                ("nom", models.CharField(max_length=6)),
            ],
        ),
    ]
