# Generated by Django 4.1.7 on 2023-05-05 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0003_personnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run Windows"),
                    ("MAC", "MAC - Run MacOS"),
                    ("Serveur", "Serveur Simple server to deploy Run Windows"),
                    ("Switch", "Switch to maintain and connects servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 5, 8, 44, 18, 881471)
            ),
        ),
    ]
