# Generated by Django 4.1.7 on 2023-05-05 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0004_machine_mach_machine_maintenancedate"),
    ]

    operations = [
        migrations.CreateModel(
            name="get_object_or_404",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("prenom", models.CharField(max_length=6)),
                ("nom", models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 5, 9, 34, 7, 868198)
            ),
        ),
    ]
